24pullrequests/contribulator

Gemfile, Gemfile.lock, app/controllers/projects_controller.rb, app/views/projects/index.html.erb
Implementation for  #15. Shall we go for endless scrolling? or is this good?
=> Added basic pagination for projects

app/assets/javascripts/notices.coffee, app/assets/javascripts/notices.js, app/controllers/projects_controller.rb, app/views/layouts/application.html.erb
=> add a notice if a project has already been added and redirect to it.

app/controllers/projects_controller.rb, app/models/project.rb
behaviour in the show action but allow us to fall back gracefully on the
create action to a find-or-create behaviour.
#43
=> add a bang version of the find project method to allow for existing 404

app/assets/stylesheets/application.css.scss, app/views/issues/_issue.html.erb, app/views/issues/show.html.erb, app/views/projects/show.html.erb
=> Hide issue bodies on mobile

config/initializers/faraday.rb
This relates to plataformatec/faraday-http-cache#38 and resolves #44
=> Use Marshal for faraday serializer.

app/controllers/projects_controller.rb
The simplest approach, don't do anything punishing (like a full 404)
A future idea might be to do a fuzzy search based on similar projects and do a 'did you mean' style thing.
=> rescues from Octokit::NotFound and returns the user with a flash

CODE_OF_CONDUCT.md, CONTRIBUTING.md, Readme.md, app/controllers/users_controller.rb, app/views/users/show.html.erb, config/initializers/i18n_setup.rb, config/locales/en.yml, config/locales/models/user/en.yml, config/locales/views/users/en.yml, db/seeds.rb
* Shortened lines in .md files (helps to make these more editor friendly)
* Initial overhaul of users controller (initialised user object, added null checking)
* Start of translation overhaul
* translations under `/config/locales/views` and `/config/locales/models`
* translations in place for user controller
* initial seed data
=> MD tidying and initial overhaul of users controller

CODE_OF_CONDUCT.md, CONTRIBUTING.md, Readme.md, app/controllers/users_controller.rb, app/views/layouts/application.html.erb, app/views/projects/index.html.erb, app/views/projects/new.html.erb, app/views/projects/show.html.erb, app/views/search/index.html.erb, app/views/users/show.html.erb, config/environments/test.rb, config/initializers/i18n_setup.rb, config/locales/en.yml, config/locales/models/issues/en.yml, config/locales/models/project/en.yml, config/locales/models/user/en.yml, config/locales/views/issues/en.yml, config/locales/views/layouts/en.yml, config/locales/views/projects/en.yml, config/locales/views/search/en.yml, config/locales/views/users/en.yml, db/schema.rb, db/seeds.rb
Translations for all untranslated strings
* Models translated
* Views translated
* Checked in schema.rb (allows `rake db:setup` from a dropped database)
* import task mentioned in readme
(also changes from my master, but there's a separate pull request for that)
=> Initial translations

Guardfile, app/assets/stylesheets/issues.scss, app/models/issue.rb, app/views/issues/_issue.html.erb, config/initializers/faraday.rb, db/migrate/20150416194709_add_number_to_issues.rb, db/schema.rb, lib/tasks/projects.rake, spec/controllers/issues_controller_spec.rb, spec/factories.rb, spec/fixtures/vcr_cassettes/Issue/can_fetch_labels_for_the_given_issue.yml, spec/fixtures/vcr_cassettes/IssuesController/GET_show/fetches_labels_for_the_issue_into_labels.yml, spec/fixtures/vcr_cassettes/IssuesController/GET_show/loads_all_of_the_issue_into_issue.yml, spec/fixtures/vcr_cassettes/IssuesController/GET_show/renders_the_index_template.yml, spec/fixtures/vcr_cassettes/IssuesController/GET_show/responds_successfully_with_an_HTTP_200_status_code.yml, spec/fixtures/vcr_cassettes/issue-labels.yml, spec/fixtures/vcr_cassettes/rails-issue-labels.yml, spec/models/issue_spec.rb, spec/rails_helper.rb
also faraday wasn't actually caching properly, so now it is, otherwise
performance is dreadful for project#show
closes #25
=> add labels method to issue model. display issues on project show page

app/controllers/projects_controller.rb, app/models/github_project.rb, app/views/projects/confirm.html.erb, config/locales/views/projects/en.yml, config/routes.rb, spec/controllers/projects_controller_spec.rb
adds confirm step relating to #49
=> Prompt for confirmation on adding a project not already imported

spec/controllers/issues_controller_spec.rb, spec/controllers/pages_controller_spec.rb, spec/controllers/projects_controller_spec.rb, spec/models/issue_spec.rb, spec/models/project_spec.rb, spec/models/score_calculator_spec.rb, spec/rails_helper.rb
fixed hash syntax to Ruby 1.9 syntax
=> fixed hash syntax

Gemfile.lock
Upgraded crack gem by rebuilding Gemfile.lock file.
=> Upgraded crack gem

Gemfile.lock
* Upgraded bugsnag and sprockets gems. 
* Fixed #89 and #90.
* Also following were fixed by previous PRs: #82, #83, #86.
=> Upgraded bugsnag and sprockets gems. 

Gemfile, Gemfile.lock
* Upgraded web-console and bundler gems.
* Also moved web-console out of :test block in Gemfile file.
=> Upgraded web-console gem

Gemfile.lock
=> Upgraded spring gem.

Gemfile.lock
=> Upgraded coffee-rails gem

Gemfile.lock
=> Upgraded bugsnag gem

Gemfile.lock
=> Upgraded redcarpet gem

Gemfile.lock
Upgraded autoprefixer-rails gem.
=> Upgraded autoprefixer-rails gem

Gemfile.lock
=> Update webmock gem to version 1.24.5

.env.example, Gemfile, Gemfile.lock, Readme.md
=> Add dotenv to manage environment variables on dev

Gemfile, Gemfile.lock, db/migrate/20160421143043_add_indexes_to_projects.rb, db/schema.rb
Suggested indexes on #53 were added:
* score;
* name;
* owner;
* main_language;
* last_scored.
=> Add indexes on projects tables

app/views/projects/new.html.erb
=> Add classes to style new project form

Gemfile, Gemfile.lock
Fixes #296
Fixes #297
Fixes #298
=> Remove explicit its-it requirement

Gemfile.lock, app/models/score_calculator.rb
=> Fix issue count in score calculator

app/models/project.rb
Fixes #67 and potentially https://github.com/24pullrequests/24pullrequests/issues/1631
=> Re-fetch owner if repo has moved location
